# Generated by Django 4.1 on 2022-09-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacttracers',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'contacttracers',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('nric', models.TextField(unique=True)),
                ('name', models.TextField()),
                ('dob', models.DateField()),
                ('email', models.TextField(blank=True)),
                ('phone', models.IntegerField()),
                ('gender', models.TextField()),
                ('address', models.TextField()),
                ('postal_code', models.TextField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Infectionhistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_timestamp', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infections.users')),
            ],
            options={
                'db_table': 'infectionhistory',
                'unique_together': {('user', 'recorded_timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Closecontacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_timestamp', models.DateTimeField()),
                ('rssi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contacted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacted_user', to='infections.users')),
                ('infected_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='infected_user', to='infections.users')),
                ('infectionhistory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infections.infectionhistory')),
            ],
            options={
                'db_table': 'closecontacts',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('due_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('infection', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infections.infectionhistory')),
                ('uploaded_status', models.BooleanField(blank=True, null=True)),
                ('tracer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infections.contacttracers')),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
    ]
